vich_uploader:
    db_driver: orm

    mappings :
        warrior_image :
            uri_prefix : /images/warriors
            upload_destination: '%kernel.project_dir%/public/images/warriors'
            namer : Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
